// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEU7R6ZM03MrbY-hlpRSs-dq5JkGXFc7Q',
    appId: '1:493141574856:web:fd53c4bc161c92572611fd',
    messagingSenderId: '493141574856',
    projectId: 'app-s-2e8c3',
    authDomain: 'app-s-2e8c3.firebaseapp.com',
    storageBucket: 'app-s-2e8c3.firebasestorage.app',
    measurementId: 'G-EJB2Q127FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgYsF7D5Ln1XMKI2uOqGeL0pQdMcr4Nig',
    appId: '1:493141574856:android:902da963d9ca49252611fd',
    messagingSenderId: '493141574856',
    projectId: 'app-s-2e8c3',
    storageBucket: 'app-s-2e8c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh6PV2AROgihOCA4eE84N7ExJOeVEZFBs',
    appId: '1:493141574856:ios:680b49c50039091d2611fd',
    messagingSenderId: '493141574856',
    projectId: 'app-s-2e8c3',
    storageBucket: 'app-s-2e8c3.firebasestorage.app',
    androidClientId: '493141574856-2if0con67nfvjnqo40g9vadrnktdiv3e.apps.googleusercontent.com',
    iosClientId: '493141574856-jsipjr25esqthb36atetncb9lhdqb986.apps.googleusercontent.com',
    iosBundleId: 'com.example.tadween',
  );
}
